# Generated by Django 3.2.16 on 2022-12-09 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('years_of_experience', models.CharField(choices=[('LESS THAN 1 YEAR', 'Less than 1 year'), ('1 YEAR', '1 Year'), ('2 YEAR', '2 Year'), ('3 YEAR', '3 Year'), ('4 YEAR', '4 Year'), ('5 OR MORE YEAR', '5 or More year')], default=None, max_length=50)),
                ('favourite_programming_language', models.CharField(choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('JAVASCRIPT', 'Javascript'), ('PYTHON', 'python'), ('JAVA', 'Java'), ('C AND C++', 'C and C++'), ('PHP', 'PHP'), ('C#', 'C#')], default=None, max_length=20)),
                ('about_me', models.TextField(blank=True)),
                ('image', models.ImageField(default='../default_profile_sgymh1', upload_to='images/')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
