# Generated by Django 3.2.16 on 2022-12-05 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=55)),
                ('favourite_programming_language', models.CharField(choices=[('HTML', 'html'), ('CSS', 'css'), ('Javascript', 'javascript'), ('Python', 'python'), ('Java', 'java'), ('Other', 'other')], default=None, max_length=20)),
                ('about_me', models.TextField(blank=True)),
                ('image', models.ImageField(default='../default_profile_sgymh1', upload_to='images/')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
