# Generated by Django 3.2.16 on 2022-12-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favourite_programming_language',
            field=models.CharField(choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('JAVASCRIPT', 'Javascript'), ('PYTHON', 'python'), ('JAVA', 'Java'), ('C AND C++', 'C and C++'), ('PHP', 'PHP'), ('C#', 'C#')], default=None, max_length=20),
        ),
    ]
