# Generated by Django 3.2.16 on 2022-12-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_years_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favourite_programming_language',
            field=models.CharField(blank=True, choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('JAVASCRIPT', 'Javascript'), ('PYTHON', 'python'), ('JAVA', 'Java'), ('C AND C++', 'C and C++'), ('PHP', 'PHP'), ('C#', 'C#')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='years_of_experience',
            field=models.CharField(blank=True, choices=[('LESS THAN 1 YEAR', 'Less than 1 year'), ('1 YEAR', '1 Year'), ('2 YEAR', '2 Year'), ('3 YEAR', '3 Year'), ('4 YEAR', '4 Year'), ('5 OR MORE YEAR', '5 or More year')], max_length=50),
        ),
    ]
