# Generated by Django 3.2.16 on 2022-12-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20221209_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='years_of_experience',
            field=models.CharField(blank=True, choices=[('LESS THAN 1 YEAR', 'Less than 1 year'), ('1 YEAR', '1 Year'), ('2 YEARS', '2 Years'), ('3 YEARS', '3 Years'), ('4 YEARS', '4 Years'), ('5 OR MORE YEARS', '5 or More years')], max_length=50),
        ),
    ]
