# Generated by Django 3.2.16 on 2022-12-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_years_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favourite_programming_language',
            field=models.CharField(blank=True, choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('Javascript', 'Javascript'), ('python', 'python'), ('Java', 'Java'), ('C and C++', 'C and C++'), ('PHP', 'PHP'), ('C#', 'C#')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='years_of_experience',
            field=models.CharField(blank=True, choices=[('Less than 1 year', 'Less than 1 year'), ('1 Year', '1 Year'), ('2 Years', '2 Years'), ('3 Years', '3 Years'), ('4 Years', '4 Years'), ('5 or More years', '5 or More years')], max_length=50),
        ),
    ]
