# Generated by Django 3.2.16 on 2023-01-18 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='select_reason',
            new_name='add_reason',
        ),
    ]
